<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Teacher;
use App\Notifications\SystemNotification;
use App\Services\ActivityLogService;
use App\Helpers\ImageOptimizer;
// use App\Models\ClassRoom;
// use App\Models\TeacherSubject;
use Illuminate\Http\Request;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Reader\Csv;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TeacherController extends Controller
{
    public function index(Request $request)
    {
        $query = User::where('role', 'guru')->with('teacher');

        if ($request->filled('search')) {
            $search = $request->search;
            $query->where(function($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('teacher_code', 'like', "%{$search}%")
                  ->orWhere('phone', 'like', "%{$search}%");
            });
        }

        if ($request->filled('status')) {
            if ($request->status === 'active') {
                $query->where('is_active', true);
            } elseif ($request->status === 'inactive') {
                $query->where('is_active', false);
            }
        }

        $teachers = $query->orderBy('name', 'asc')->paginate(15)->withQueryString();

        $stats = [
            'total' => User::where('role', 'guru')->count(),
            'active' => User::where('role', 'guru')->where('is_active', true)->count(),
            'inactive' => User::where('role', 'guru')->where('is_active', false)->count(),
            'today_checkin' => User::where('role', 'guru')
                ->whereHas('attendances', function($q) {
                    $q->where('date', today());
                })->count(),
        ];

        return view('teachers.index', compact('teachers', 'stats'));
    }

    public function create()
    {
        $subjects = \App\Models\Subject::where('is_active', true)->orderBy('name')->get();

        return view('teachers.create', compact('subjects'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'teacher_code' => ['required', 'string', 'max:50', 'unique:users,teacher_code'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'confirmed', Rules\Password::defaults()],
            'phone' => ['nullable', 'string', 'max:20'],
            'photo' => ['nullable', 'image', 'mimes:jpeg,png,jpg', 'max:2048'],
            'address' => ['nullable', 'string', 'max:500'],
            'bio' => ['nullable', 'string', 'max:500'],
            'subject' => ['nullable', 'string', 'max:255'],
            'start_time' => ['nullable', 'date_format:H:i'],
            'end_time' => ['nullable', 'date_format:H:i'],
        ]);

        $photoPath = null;
        if ($request->hasFile('photo')) {
            $photoPath = ImageOptimizer::store($request->file('photo'), 'profiles/' . $request->file('photo')->hashName());
        }

        $employeeCode = null;
        DB::transaction(function () use ($validated, $photoPath, &$employeeCode) {
            $user = User::create([
                'name' => $validated['name'],
                'teacher_code' => $validated['teacher_code'],
                'email' => $validated['email'],
                'password' => Hash::make($validated['password']),
                'role' => 'guru',
                'photo' => $photoPath,
                'phone' => $validated['phone'] ?? null,
                'address' => $validated['address'] ?? null,
                'bio' => $validated['bio'] ?? null,
                'subject' => $validated['subject'] ?? null,
                'start_time' => $validated['start_time'] ?? '07:30',
                'end_time' => $validated['end_time'] ?? '16:00',
                'is_active' => true,
            ]);

            $user->generateQrCode();

            // Create Teacher record (employee_code auto-generated by model)
            $teacher = Teacher::create([
                'user_id' => $user->id,
                'name' => $validated['name'],
                'email' => $validated['email'],
                'phone' => $validated['phone'] ?? null,
                'address' => $validated['address'] ?? null,
                'major_specialty' => $validated['subject'] ?? null,
                'is_active' => true,
            ]);

            $employeeCode = $teacher->employee_code;
        });

        // Send notification
        $admins = User::whereIn('role', ['admin', 'operator'])->get();
        foreach ($admins as $admin) {
            /** @var User $admin */
            $admin->notify(new SystemNotification(
                "Data guru baru ({$validated['name']}) berhasil ditambahkan dengan ID: {$employeeCode}.",
                'info',
                route('teachers.index')
            ));
        }

        try { ActivityLogService::teacherCreated(auth()->user(), $user); } catch (\Exception $e) {}

        return redirect()->route('teachers.index')->with('success', "Guru berhasil ditambahkan dengan ID: {$employeeCode}!");
    }

    public function show(User $teacher, Request $request)
    {
        if ($teacher->role !== 'guru') {
            abort(403);
        }

        // Load teacher relation
        $teacher->load('teacher');

        // $teacher->load(['activeSubjects' => function($query) {
        //     $query->withPivot('class_id', 'semester', 'academic_year', 'hours_per_week');
        // }]);
        
        $attendances = $teacher->attendances()
            ->latest('check_in')
            ->paginate(5);
        
        $stats = [
            'total_hadir' => $teacher->attendances()->where('status', 'Hadir')->count(),
            'total_terlambat' => $teacher->attendances()->where('status', 'Terlambat')->count(),
            'total_izin' => $teacher->attendances()->where('status', 'Izin')->count(),
            'total_alpha' => $teacher->attendances()->where('status', 'Alpha')->count(),
        ];

        // Fetch subject details for description
        $subjectDetails = null;
        if ($teacher->subject) {
            $subjectDetails = \App\Models\Subject::where('name', $teacher->subject)->first();
        }

        // If AJAX request, return only the attendance body and pagination
        if ($request->header('X-Requested-With') === 'XMLHttpRequest') {
            return response()->json([
                'body' => view('teachers.partials.attendance-body', compact('attendances'))->render(),
                'pagination' => view('teachers.partials.attendance-pagination', compact('attendances'))->render(),
            ]);
        }

        return view('teachers.show', compact('teacher', 'attendances', 'stats', 'subjectDetails'));
    }

    public function edit(User $teacher)
    {
        if ($teacher->role !== 'guru') {
            abort(403);
        }

        // Load teacher relation
        $teacher->load('teacher');

        // Fetch active subjects dynamically
        $subjects = \App\Models\Subject::where('is_active', true)->orderBy('name')->get();
        
        $teacherSubject = $teacher->subject;
        
        return view('teachers.edit', compact('teacher', 'subjects', 'teacherSubject'));
    }

    public function update(Request $request, User $teacher)
    {
        if ($teacher->role !== 'guru') {
            abort(403);
        }

        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'teacher_code' => 'required|string|max:50|unique:users,teacher_code,' . $teacher->id,
            'email' => 'required|email|unique:users,email,' . $teacher->id,
            'password' => 'nullable|min:6',
            'phone' => 'nullable|string|max:20',
            'address' => 'nullable|string',
            'subject' => 'nullable|string|max:255',
            'is_active' => 'nullable|boolean',
            'photo' => 'nullable|image|mimes:jpeg,png,jpg|max:2048',
        ]);

        $updateData = [
            'name' => $validated['name'],
            'teacher_code' => $validated['teacher_code'],
            'email' => $validated['email'],
            'phone' => $validated['phone'] ?? null,
            'address' => $validated['address'] ?? null,
            'subject' => $validated['subject'] ?? null,
            'is_active' => $request->has('is_active') ? (bool)$validated['is_active'] : $teacher->is_active,
        ];

        if (!empty($validated['password'])) {
            $updateData['password'] = Hash::make($validated['password']);
        }

        if ($request->hasFile('photo')) {
            if ($teacher->photo) {
                Storage::disk('public')->delete($teacher->photo);
            }
            $photoPath = ImageOptimizer::replace($request->file('photo'), $teacher->photo, 'profiles/' . $request->file('photo')->hashName());
            $updateData['photo'] = $photoPath;
            
            // Pastikan file tersimpan
            \Illuminate\Support\Facades\Log::info('Teacher photo updated', [
                'teacher_id' => $teacher->id,
                'path' => $photoPath,
                'exists' => Storage::disk('public')->exists($photoPath),
            ]);
        }

        $teacher->update($updateData);

        // ActivityLog
        try { ActivityLogService::teacherUpdated(auth()->user(), $teacher, array_keys($updateData)); } catch (\Exception $e) {}

        // Update teacher record (sync major_specialty with subject)
        if ($teacher->teacher) {
            $oldMajorSpecialty = $teacher->teacher->major_specialty;
            $newMajorSpecialty = $validated['subject'] ?? null;
            
            $teacher->teacher->update([
                'name' => $validated['name'],
                'email' => $validated['email'],
                'phone' => $validated['phone'] ?? null,
                'address' => $validated['address'] ?? null,
                'major_specialty' => $newMajorSpecialty,
                'is_active' => $request->has('is_active') ? (bool)$request->is_active : $teacher->is_active,
            ]);
            
            // Auto-sync to subject_teacher pivot table when major_specialty changes
            if ($oldMajorSpecialty !== $newMajorSpecialty) {
                // Remove ALL old subject mappings (untuk guru ini)
                // Karena kita mau replace dengan yang baru
                $teacher->teacher->subjects()->detach();
                
                // Add new subject mapping
                if ($newMajorSpecialty) {
                    $newSubject = \App\Models\Subject::where('name', 'LIKE', '%' . $newMajorSpecialty . '%')->first();
                    
                    // Fallback: coba cari dengan case-insensitive exact match
                    if (!$newSubject) {
                        $newSubject = \App\Models\Subject::whereRaw('LOWER(name) = ?', [strtolower($newMajorSpecialty)])->first();
                    }
                    
                    if ($newSubject) {
                        $teacher->teacher->subjects()->attach($newSubject->id);
                    }
                }
            }
        }

        return redirect()->route('teachers.edit', $teacher)
            ->with('success', 'Data guru berhasil diperbarui' . ($request->hasFile('photo') ? ' (termasuk foto profil)' : ''));
    }

    public function importExcel(Request $request)
    {
        $request->validate([
            'file' => 'required|file|mimes:xlsx,xls,csv|max:2048',
        ]);

        try {
            set_time_limit(0);
            ini_set('max_execution_time', '0');

            $file = $request->file('file');
            $filePath = $file->getRealPath();

            $spreadsheet = IOFactory::load($filePath);
            $worksheet = $spreadsheet->getActiveSheet();
            $rows = $worksheet->toArray();

            if (empty($rows)) {
                return redirect()->route('teachers.index')
                    ->with('error', 'File Excel kosong!');
            }

            $header = array_shift($rows);

            $expectedHeaders = ['nama', 'kode_guru'];
            $normalizedHeaders = array_map(function ($h) {
                return strtolower(trim(str_replace(['_', ' '], '', $h)));
            }, $header);

            if (!in_array('nama', $normalizedHeaders) || !in_array('kodeguru', $normalizedHeaders)) {
                return redirect()->route('teachers.index')
                    ->with('error', 'Format file tidak sesuai. Kolom harus: nama, kode_guru');
            }

            $namaIndex = array_search('nama', $normalizedHeaders);
            $kodeIndex = array_search('kodeguru', $normalizedHeaders);

            $successCount = 0;
            $errorCount = 0;
            $errors = [];
            $defaultPasswordHash = Hash::make('password123');

            foreach ($rows as $index => $row) {
                $rowNumber = $index + 2;
                if (empty($row[$namaIndex]) && empty($row[$kodeIndex])) {
                    continue;
                }

                $validator = Validator::make([
                    'nama' => $row[$namaIndex] ?? null,
                    'kode_guru' => $row[$kodeIndex] ?? null,
                ], [
                    'nama' => 'required|string|max:255',
                    'kode_guru' => 'required|string|max:50|unique:users,teacher_code',
                ]);

                if ($validator->fails()) {
                    $errorCount++;
                    $errors[] = "Baris {$rowNumber}: " . implode(', ', $validator->errors()->all());
                    continue;
                }

                try {
                    DB::transaction(function () use ($row, $namaIndex, $kodeIndex, &$user, $defaultPasswordHash) {
                        $user = User::create([
                            'name' => $row[$namaIndex],
                            'teacher_code' => $row[$kodeIndex],
                            'email' => strtolower(trim($row[$kodeIndex])) . '@icbct.sch.id',
                            'password' => $defaultPasswordHash,
                            'role' => 'guru',
                            'is_active' => true,
                        ]);

                        if ($user->role === 'guru') {
                            $user->generateQrCode();

                            Teacher::create([
                                'user_id' => $user->id,
                                'employee_code' => Teacher::generateEmployeeCode(),
                                'name' => $user->name,
                                'email' => $user->email,
                                'phone' => null,
                                'address' => null,
                                'major_specialty' => null,
                                'is_active' => true,
                            ]);
                        }
                    });

                    $successCount++;
                } catch (\Exception $e) {
                    $errorCount++;
                    $errors[] = "Baris {$rowNumber}: Gagal menyimpan - " . $e->getMessage();
                }
            }

            $errorSummary = count($errors) > 5
                ? implode('; ', array_slice($errors, 0, 5)) . '... dan ' . (count($errors) - 5) . ' error lainnya'
                : implode('; ', $errors);

            if ($successCount > 0 && $errorCount > 0) {
                return redirect()->route('teachers.index')
                    ->with('success', "Import selesai! {$successCount} berhasil, {$errorCount} gagal.")
                    ->with('errors', $errorSummary);
            } elseif ($successCount > 0) {
                return redirect()->route('teachers.index')
                    ->with('success', "Import berhasil! {$successCount} guru ditambahkan.");
            }

            return redirect()->route('teachers.index')
                ->with('error', "Import gagal. Semua baris error: {$errorSummary}");

        } catch (\PhpOffice\PhpSpreadsheet\Reader\Exception $e) {
            return redirect()->route('teachers.index')
                ->with('error', 'Gagal membaca file Excel: ' . $e->getMessage());
        } catch (\Exception $e) {
            return redirect()->route('teachers.index')
                ->with('error', 'Import gagal: ' . $e->getMessage());
        }
    }

    public function downloadTemplate()
    {
        $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
        $worksheet = $spreadsheet->getActiveSheet();

        $worksheet->setCellValue('A1', 'nama');
        $worksheet->setCellValue('B1', 'kode_guru');

        $worksheet->setCellValue('A2', 'Contoh Nama Guru');
        $worksheet->setCellValue('B2', 'TSM-01');
        $worksheet->setCellValue('A3', 'John Doe');
        $worksheet->setCellValue('B3', 'RPL-02');

        $worksheet->getStyle('A1:B1')->getFont()->setBold(true);
        $worksheet->getStyle('A1:B1')->getFill()
            ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
            ->getStartColor()->setARGB('FF0F172A');
        $worksheet->getStyle('A1:B1')->getFont()->getColor()->setARGB('FFFFFFFF');

        $worksheet->getColumnDimension('A')->setWidth(30);
        $worksheet->getColumnDimension('B')->setWidth(15);

        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $fileName = 'template_import_guru.xlsx';

        return response()->stream(function () use ($writer) {
            $writer->save('php://output');
        }, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => 'attachment; filename="' . $fileName . '"',
        ]);
    }

    public function destroy(User $teacher)
    {
        if ($teacher->role !== 'guru') {
            abort(403);
        }

        DB::transaction(function () use ($teacher) {
            if ($teacher->photo) {
                Storage::disk('public')->delete($teacher->photo);
            }

            $teacher->attendances()->delete();
            \App\Models\ClassAttendance::where('user_id', $teacher->id)->delete();
            \App\Models\TeachingSchedule::where('user_id', $teacher->id)->delete();
            \App\Models\TeacherSchedule::where('user_id', $teacher->id)->delete();
            $teacher->delete();
        });

        // Send notification
        $admins = User::whereIn('role', ['admin', 'operator'])->get();
        foreach ($admins as $admin) {
            /** @var User $admin */
            $admin->notify(new SystemNotification(
                "Data guru ({$teacher->name}) telah dihapus dari sistem.",
                'warning'
            ));
        }

        try { ActivityLogService::teacherDeleted(auth()->user(), $teacher); } catch (\Exception $e) {}

        return redirect()->route('teachers.index')->with('success', 'Guru berhasil dihapus!');
    }

    public function toggleStatus(User $teacher)
    {
        if ($teacher->role !== 'guru') {
            abort(403);
        }

        DB::transaction(function () use ($teacher) {
            $teacher->update(['is_active' => !$teacher->is_active]);
        });
        
        $status = $teacher->is_active ? 'diaktifkan' : 'dinonaktifkan';
        return back()->with('success', "Guru berhasil {$status}!");
    }

    public function bulkToggleStatus(Request $request)
    {
        $validated = $request->validate([
            'teacher_ids' => ['required', 'array', 'min:1'],
            'teacher_ids.*' => ['integer', 'exists:users,id'],
            'status' => ['required', 'in:0,1'],
        ]);

        $ids = array_unique($validated['teacher_ids']);
        $isActive = $validated['status'] === '1';

        $count = User::where('role', 'guru')
            ->whereIn('id', $ids)
            ->update(['is_active' => $isActive]);

        if ($count === 0) {
            return redirect()->route('teachers.index')->with('error', 'Tidak ada guru yang valid untuk diperbarui.');
        }

        $label = $isActive ? 'diaktifkan' : 'dinonaktifkan';

        return redirect()->route('teachers.index')->with('success', "{$count} guru berhasil {$label}.");
    }

    public function bulkDelete(Request $request)
    {
        $validated = $request->validate([
            'teacher_ids' => ['required', 'array', 'min:1'],
            'teacher_ids.*' => ['integer', 'exists:users,id'],
        ]);

        $ids = array_unique($validated['teacher_ids']);
        $teachers = User::where('role', 'guru')->whereIn('id', $ids)->get();

        if ($teachers->isEmpty()) {
            return redirect()->route('teachers.index')->with('error', 'Tidak ada guru yang valid untuk dihapus.');
        }

        DB::transaction(function () use ($teachers) {
            foreach ($teachers as $teacher) {
                /** @var User $teacher */
                if ($teacher->photo) {
                    Storage::disk('public')->delete($teacher->photo);
                }
                // TeacherSubject::where('user_id', $teacher->id)->delete();
                $teacher->attendances()->delete();
                $teacher->delete();
            }
        });

        $n = $teachers->count();

        return redirect()->route('teachers.index')->with('success', "{$n} guru berhasil dihapus.");
    }

    public function getData(User $teacher)
    {
        if ($teacher->role !== 'guru') {
            return response()->json(['error' => 'Not a teacher'], 403);
        }

        return response()->json([
            'id' => $teacher->id,
            'name' => $teacher->name,
            'email' => $teacher->email,
            'subject' => $teacher->subject,
        ]);
    }
}